// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxEC-nJWeJIDOzG6tSkQGn6fItoDtTaLg',
    appId: '1:647126052008:web:20f1c2b59c6cd6274ae69d',
    messagingSenderId: '647126052008',
    projectId: 'samo-a927b',
    authDomain: 'samo-a927b.firebaseapp.com',
    storageBucket: 'samo-a927b.firebasestorage.app',
    measurementId: 'G-8BFJW947Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUN3_iRgyH9XmElyLyoO_FrjuSzaP5i0Y',
    appId: '1:647126052008:android:449b874f27a0e21f4ae69d',
    messagingSenderId: '647126052008',
    projectId: 'samo-a927b',
    storageBucket: 'samo-a927b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIu4isvZs4kz4G80zulxNRRytZUr2z8hI',
    appId: '1:647126052008:ios:e69b9017656bf8e84ae69d',
    messagingSenderId: '647126052008',
    projectId: 'samo-a927b',
    storageBucket: 'samo-a927b.firebasestorage.app',
    iosBundleId: 'com.nexta.etacherv4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIu4isvZs4kz4G80zulxNRRytZUr2z8hI',
    appId: '1:647126052008:ios:e69b9017656bf8e84ae69d',
    messagingSenderId: '647126052008',
    projectId: 'samo-a927b',
    storageBucket: 'samo-a927b.firebasestorage.app',
    iosBundleId: 'com.nexta.etacherv4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxEC-nJWeJIDOzG6tSkQGn6fItoDtTaLg',
    appId: '1:647126052008:web:d3f7a103fdfd2bc04ae69d',
    messagingSenderId: '647126052008',
    projectId: 'samo-a927b',
    authDomain: 'samo-a927b.firebaseapp.com',
    storageBucket: 'samo-a927b.firebasestorage.app',
    measurementId: 'G-VPJRQXNGPQ',
  );
}
